import React from 'react';

const HOME = () => {
    return (
        <div className='mt-24 mx-32 text-3xl font-light leading-loose'>
            Welcome to Home
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis odio voluptas autem nihil assumenda qui deleniti omnis eos fuga laboriosam, aperiam mollitia dolorum nisi neque, dolore illum officiis quos error!
            In eaque eligendi beatae numquam consectetur sint autem atque, rem ratione vitae hic expedita praesentium doloremque iste ad cupiditate porro laborum corrupti quod impedit corporis libero eveniet? Impedit, nihil facere!
            Perferendis debitis vero architecto voluptatibus, sunt aperiam. Neque a veritatis ab asperiores cumque repellat voluptatem soluta eaque esse molestiae. Dolore ut pariatur fugiat. Officia esse aspernatur, impedit eveniet quibusdam sequi?
            Maxime obcaecati est, numquam voluptatem placeat error quidem eaque voluptate saepe eum. Blanditiis pariatur, quos velit iusto distinctio odio eos praesentium fugit nesciunt eius! Placeat, rem odit? Omnis, harum consequatur.
            Quidem tempore totam est, quisquam sequi minus maxime ut dicta adipisci corporis non voluptate beatae consequuntur perspiciatis alias nulla doloribus deserunt! Eligendi unde dolor soluta dicta amet temporibus dolores voluptas.
            Rem harum modi expedita pariatur nesciunt. Provident quo distinctio porro autem laudantium alias reiciendis esse corrupti praesentium. Repellendus aperiam dolorem natus iure. Sapiente eveniet nulla maxime eligendi, repellendus sit modi.
            Eveniet commodi beatae repellat assumenda accusamus aliquam a praesentium, alias nam facilis, quasi rerum voluptate sunt minima reiciendis non ipsa esse repellendus rem numquam obcaecati autem. Minima suscipit facilis officia.
            Cumque facere itaque quaerat explicabo ipsum reprehenderit eius fugiat, praesentium perspiciatis voluptatibus, magnam quo facilis? Cum, expedita natus. Veniam laborum dicta nulla sint officiis consequuntur quasi amet tempore, nemo sunt.
            Consectetur, quam, praesentium voluptates aperiam laborum non quidem doloremque animi reiciendis voluptatem facilis illo tempore vero corrupti cupiditate. Eligendi quibusdam ipsa id. Doloremque exercitationem ut, aliquam illum possimus vitae est?
            Possimus quibusdam ipsa praesentium? Molestiae perspiciatis quidem officia sequi excepturi sapiente iusto? Quia libero, ad eius quod autem ducimus ex assumenda! Itaque non repellat voluptate, quod expedita ea quos laboriosam!
            Ab recusandae perferendis sed, atque saepe laboriosam incidunt? Perspiciatis repellendus nesciunt, saepe expedita repellat laboriosam repudiandae nulla non molestias impedit corporis minima voluptatum! Labore eaque necessitatibus culpa molestias ipsam inventore?
            Voluptas blanditiis corporis, consectetur quibusdam veritatis velit? Ab nostrum necessitatibus iste quaerat corrupti voluptatem blanditiis vero distinctio, neque molestiae unde, magni sed debitis, assumenda tenetur inventore nobis ex aliquam minus.
            Ut nulla sequi ad aliquid dignissimos voluptatum quos neque voluptatem iusto labore! Quisquam dolores repellat, tempore, reprehenderit nemo dignissimos incidunt earum reiciendis nihil quas asperiores animi obcaecati officiis? Minus, dolorem.
            Mollitia, iure numquam repudiandae distinctio ipsam obcaecati doloribus, iusto tenetur voluptas sequi quae possimus rerum eligendi sed sunt quas dolorum nulla exercitationem rem quos? Nemo exercitationem ex laborum ipsam corrupti.
            Molestias impedit, incidunt sapiente voluptatibus temporibus doloribus iure numquam veniam neque fugiat pariatur omnis. Quaerat error quam asperiores inventore. Laborum accusamus velit excepturi tenetur hic voluptate, accusantium similique odit dolor.
            Tenetur id ea quia similique quasi voluptate aperiam inventore. Architecto esse ratione nihil voluptatem earum dignissimos porro animi quaerat sit debitis magnam nemo tempora hic asperiores, doloremque perspiciatis sed. Dicta.
            Vero cupiditate, esse officiis voluptate placeat libero. Omnis assumenda id corporis. Neque eaque deserunt itaque quaerat tempora adipisci nobis sunt, laborum soluta quo, ipsum inventore. Omnis non et amet illo!
            Vero, aspernatur facere laborum eum unde culpa quo nostrum cupiditate perferendis quidem accusamus dicta, impedit accusantium. Nisi, nobis voluptatem, consectetur impedit dolor tempore sit numquam optio, eaque fuga vel nesciunt?
            Ipsam tempore quibusdam odit nihil, voluptatem voluptas ratione minima laudantium itaque. Consectetur asperiores autem provident consequatur esse, molestiae odit fuga, impedit accusamus cupiditate qui pariatur repudiandae repellat sint minus dolore!
            Assumenda perspiciatis ratione voluptatem dolor minus, beatae, quod, tempore voluptas dolorum nisi sunt vero. Praesentium, itaque veritatis ipsam amet, quam ipsa nam modi perferendis ab, voluptas delectus? Minus, quae fugit!
            Illo quia id reprehenderit libero aliquid nisi doloremque, ex eum repellat alias autem ipsa, voluptas nostrum unde vero ducimus! Itaque expedita illum, vel ea impedit velit. Facilis dolorum quae maiores!
            Totam minima cum obcaecati doloremque nisi vitae deserunt itaque minus saepe suscipit! Neque dignissimos vitae aliquam beatae ratione, dolore saepe unde excepturi sequi id! Provident excepturi sunt labore saepe quaerat.
            Quos porro magni, nobis corporis delectus iure soluta quisquam rem sapiente laboriosam quibusdam in dolore amet impedit voluptate ipsum veritatis, quis similique et doloremque quia sequi reiciendis necessitatibus nam! Quas?
            Beatae error, commodi hic id praesentium, quas ex autem cumque a numquam illum ducimus maiores. Eligendi velit doloremque, eveniet corrupti quis non odit magni autem pariatur eum. Molestiae, minus laudantium?
            Perferendis consequatur, numquam a ex ab omnis incidunt odio aliquid deleniti quibusdam quis sunt quaerat delectus voluptatibus, quod dolorum mollitia ea debitis! In optio velit assumenda provident molestiae dignissimos necessitatibus?
            Dolor repellat unde eaque ipsam ab modi iste provident aliquam accusamus, repellendus a veniam iure tempora iusto, cumque fugit illum odio sequi sapiente laudantium magni quaerat! Odio, numquam. Aut, voluptatem!
            Omnis iure tempora temporibus obcaecati vel at? Dicta, provident. Vero architecto, quis esse alias iste voluptatem. Corrupti quod laudantium delectus eos voluptatibus soluta, blanditiis minus? Impedit ab dignissimos distinctio ex.
            Ipsum totam officia ab nihil veniam fuga ipsa voluptate assumenda dolores? Suscipit fugit ea in totam! Obcaecati ratione ab, sapiente perspiciatis porro qui accusantium dolorem animi deserunt sunt veniam possimus.
            Quibusdam debitis quisquam at repudiandae laboriosam nostrum sint, aut cum alias minus quia magnam tenetur tempore aspernatur deserunt facere voluptatibus atque illum facilis asperiores voluptatum perferendis iure harum nesciunt? Doloremque?
            Odio earum id tempore numquam accusantium fugit, delectus sed obcaecati. Quod dolorum porro odio laboriosam tenetur. Magnam placeat error ipsam quam blanditiis provident. Officiis, commodi inventore. Ipsam exercitationem similique laudantium?
            Ullam aspernatur quos, similique dolor deserunt unde vitae illo dicta natus sed commodi, non fugiat repudiandae quidem. Quaerat quas tempora, et quam excepturi consequuntur, voluptatibus distinctio earum quidem beatae voluptate.
            Magnam repellendus est placeat ut sit quas exercitationem molestias, asperiores cum rem itaque minima consequuntur quam similique magni dolor odit quidem dignissimos ad, sint suscipit expedita dolores voluptatem? Delectus, quasi?
            Voluptatem doloribus nihil nisi quisquam obcaecati quis, tempora neque, mollitia eaque quasi nesciunt. Cum iure reprehenderit aperiam, excepturi vero inventore sint nihil at hic, ab autem repellat dolorem aliquid. Dolorem.
            Quas, mollitia vitae. Nostrum saepe numquam fugit necessitatibus similique itaque, placeat maiores architecto inventore iusto hic sed odit laudantium. Fugit omnis sapiente totam adipisci distinctio, asperiores aspernatur voluptatum blanditiis eaque.
            Nesciunt, dolore est. Placeat vel obcaecati voluptatibus eius reiciendis alias blanditiis natus eum, recusandae repudiandae quo, ratione earum debitis. Asperiores eos commodi explicabo et, est aperiam odio atque sed! Aperiam!
            Quisquam odit eum debitis praesentium ipsam voluptatem modi fugiat aut esse itaque! Dignissimos aliquid animi repellendus repellat deserunt labore facilis! Similique aliquam eius error quo debitis maiores reprehenderit laborum dolor.
            Reprehenderit rem officia ipsum provident adipisci voluptatibus? Maxime fugit in ad iste vitae, quasi, ea aliquam id ipsa aperiam quos numquam repellendus libero quis! Animi fugit minima rerum quos facilis!
            Nihil voluptas, nemo ratione dolor doloremque iste voluptatem. Officia ea exercitationem laborum omnis doloremque consequuntur, quo tempore dolorem eum, tempora unde molestias eius ut vitae labore iure. Vero, asperiores magnam!
            Totam cupiditate dolor quas provident eius temporibus, necessitatibus, aspernatur magni accusantium ipsum non? Doloremque officia voluptatum perferendis culpa minima, odit excepturi nemo nobis aperiam voluptates, maiores laborum autem a placeat?
            Voluptatibus recusandae, saepe aut neque voluptas aperiam tenetur est rerum temporibus dicta asperiores culpa ratione! Repellat, earum ullam fuga tempora vero eveniet illo nam quos expedita explicabo possimus ipsa consequuntur!
            Tempora ipsum non iure amet omnis voluptates, rem, qui magnam labore voluptatem placeat cupiditate ullam quisquam? Quod veniam temporibus voluptas, totam reiciendis vero commodi nulla, placeat ipsam rem quaerat cumque?
            Sint iure dolores blanditiis eveniet tempore rem pariatur labore, obcaecati culpa voluptates nesciunt repellendus cumque asperiores possimus commodi non quo minima quis temporibus! Non tempora doloribus quaerat quibusdam natus rem!
            Odit, at beatae? Quisquam quos harum voluptate placeat debitis aliquid, nemo reiciendis eligendi ullam rerum. Culpa eveniet, quidem laboriosam commodi sed quam non voluptates hic incidunt. Possimus voluptas nostrum quisquam?
            Temporibus doloremque deserunt necessitatibus perspiciatis odit iusto voluptatem at rerum odio assumenda suscipit praesentium, ea omnis cumque quas saepe error. Magnam sint minima alias eius quod, aperiam accusamus voluptatibus eaque.
            Itaque, laudantium inventore vitae repudiandae exercitationem distinctio quo illum cum alias! Delectus quaerat, pariatur minima, molestias eveniet ducimus accusantium consequuntur omnis animi ipsum at. Adipisci deserunt voluptatibus aspernatur saepe soluta.
            Totam, corrupti soluta libero molestias et tempore perspiciatis reprehenderit sapiente repellendus omnis voluptatem temporibus illum quas optio vero nostrum ex beatae eligendi, saepe excepturi ipsum! Fugiat nihil ad corporis est?
            Excepturi quia aspernatur quae saepe beatae aliquid dolorem harum autem reiciendis fugiat, dicta sequi. Maxime aspernatur, mollitia assumenda quo omnis inventore! Enim eos minus quibusdam, eaque cum sunt nulla sequi.
            Labore, accusantium corrupti nesciunt sint, laborum nihil quidem corporis assumenda consequatur, dolorum iste velit vel quam ad aspernatur laudantium temporibus in libero minima minus ducimus! Sequi eaque labore ipsum nulla.
            Suscipit delectus at expedita ipsum, blanditiis distinctio sunt nulla accusamus animi, aspernatur incidunt, porro laudantium ab explicabo totam culpa. Voluptates cumque consequuntur, veritatis laborum deleniti maxime ipsa obcaecati. Neque, ex.
            Nostrum qui reiciendis deserunt earum iure, reprehenderit fugit unde mollitia aspernatur dolor quod amet totam laborum provident eius, quisquam optio, officia neque. Id, quo temporibus dolorem incidunt illo magnam praesentium.
            Nam laboriosam, consequuntur commodi nihil placeat dolores, doloremque praesentium ipsa fugiat facere vero dolorum repellat illo ad libero mollitia ab maiores. Ut placeat obcaecati sed, aperiam dicta rem unde magni.
            Non, illo vel quidem ipsam iure nihil porro vero ducimus! Non deleniti sed aut illo quod ratione eos quo, doloremque consequuntur architecto praesentium quae commodi nesciunt odit explicabo sequi cumque?
            Doloremque accusamus nostrum quia quidem hic alias natus commodi rem! Sunt blanditiis ea exercitationem mollitia beatae iure placeat hic possimus est? Deserunt necessitatibus, officia alias quos dolore exercitationem id at?
            Laboriosam rem tenetur sequi perspiciatis. Possimus cupiditate sit ipsa, rem reprehenderit architecto quis eligendi reiciendis ducimus! Veniam accusantium excepturi culpa, harum debitis nihil quaerat quo molestiae quod minima maiores esse.
            Quae accusantium eos harum libero illo recusandae dolor nisi vel consectetur ea iusto quam dolores eveniet, reprehenderit fugiat in eum repudiandae similique natus quis aut id! Fugiat voluptatibus maxime pariatur?
            Fuga consectetur odit provident nobis molestias quis itaque, commodi culpa aut? Tempora, possimus dolore. Temporibus asperiores quibusdam laborum aspernatur itaque, commodi cumque animi voluptatem eaque dolor repudiandae. Maiores, voluptatem cupiditate?
            Possimus autem a nostrum totam tempora qui voluptatum, animi obcaecati nobis ab! Ducimus quae, omnis deleniti rem adipisci cum vitae temporibus aut perspiciatis facere mollitia voluptatibus nisi assumenda voluptatem velit.
            Sequi recusandae quidem ab unde voluptatibus harum accusamus illum doloribus consequuntur asperiores sit iste fugiat quam in, expedita quia ex facere similique quaerat ut sed qui laborum? Praesentium, eius suscipit.
            Quia enim facere sunt perspiciatis perferendis voluptates voluptatum? Porro, enim! Iusto, sed eius blanditiis non quis reprehenderit quasi deserunt adipisci sunt recusandae, earum ad voluptatum quas officia reiciendis necessitatibus architecto?
            Voluptates itaque eligendi, deleniti ipsam distinctio ullam quae. Iure tenetur, dolorum, hic ad molestias atque quo voluptates numquam distinctio eaque iste, unde facere laborum provident tempora blanditiis aperiam voluptatem aspernatur.
            Unde doloremque officia fuga laudantium ipsum sequi, optio id maxime? Dolores accusantium necessitatibus nostrum possimus natus similique. Possimus veritatis consectetur tempore sequi, iste fugit nobis? Maiores, libero consequatur. Totam, nam.
            Eaque veniam vitae ullam? Corrupti quis tempore dolor, veniam molestias odit exercitationem alias doloremque ducimus distinctio aliquam laboriosam sed rem eum, facilis, quae dolorum earum nobis illum. Molestias, nisi velit?
            Quaerat dolorem illo ullam cupiditate iure ad at! Aliquid fugiat quisquam perferendis? Nihil ab corporis dolor nesciunt sapiente vero, dolore laudantium cupiditate, inventore, numquam reprehenderit molestias blanditiis aspernatur praesentium perspiciatis!
            Veniam, cupiditate! Ut sequi fuga distinctio dignissimos consequatur eligendi natus autem, eveniet commodi, illo, quaerat eos. Illo nisi, distinctio laborum in illum praesentium cumque? Tenetur eligendi enim velit quibusdam voluptatibus.
            Reiciendis harum minus tempora nesciunt ea ipsum vel dignissimos sed, officia culpa quasi omnis labore aspernatur deleniti maxime ullam delectus est, esse alias. Quibusdam repellat nisi a. Debitis, consequatur perspiciatis.
            Dolorem deleniti in quos repellat deserunt labore omnis sit assumenda ullam. Dolorum harum quidem culpa at quasi porro? Saepe sunt fugiat a, beatae facere in minima perferendis voluptatum id inventore?
            Illum, necessitatibus ratione aliquid laudantium iusto inventore quidem beatae, cumque in deserunt consequuntur laborum natus fugiat enim suscipit saepe quae eligendi placeat tempora ipsam pariatur. Esse maiores ut reprehenderit animi?
            Porro esse quia magni ab id necessitatibus ipsum consectetur odit quae iste pariatur corrupti perspiciatis animi distinctio, nostrum tenetur natus. Illum quam commodi quia cumque veniam non quibusdam vitae assumenda.
            Itaque ex eum magnam atque soluta minus, recusandae odit sint dolore quis porro placeat? Omnis, adipisci maiores totam asperiores reprehenderit assumenda tempore doloribus accusamus ab maxime, quibusdam obcaecati dignissimos repudiandae.
            Quidem inventore quod necessitatibus ipsam non, totam porro. Tempore sint inventore, autem perferendis ex exercitationem id quae modi quo facere a cupiditate, dicta deleniti libero? Ab, quidem. Placeat, necessitatibus vitae?
            Sequi repellendus mollitia deserunt perferendis culpa ipsa, quod provident maiores asperiores quae eveniet tenetur ex fugiat ut sapiente? Quia maiores eligendi fugit porro mollitia sed nisi pariatur accusamus nam natus.
            Recusandae minus voluptas beatae magni, unde tempora repellat. Cumque reiciendis assumenda deleniti quia neque iste nobis facilis a voluptatibus, officiis molestias voluptas alias obcaecati accusantium vero esse consequatur molestiae ex.
            Quod obcaecati, architecto totam ipsam eum impedit tempore commodi nulla at nihil ducimus mollitia provident voluptas in. Ratione distinctio, quae ducimus quam dignissimos, officiis error aliquam perspiciatis, placeat consequatur in.
            Ad cumque architecto corporis ipsum vitae ut deserunt, ipsa in labore, maxime officiis nostrum necessitatibus laboriosam! Quo beatae tempora animi libero nobis qui ex odio, amet exercitationem dolorem odit sunt.
            Amet aspernatur neque fugit similique ea voluptatum veritatis distinctio doloribus eum, excepturi animi perspiciatis quisquam commodi necessitatibus odit eaque repellendus quas reprehenderit repellat corporis molestias ullam illo! Qui, atque perspiciatis!
            Tenetur praesentium quas pariatur dolorem, deserunt perspiciatis nesciunt, earum totam nobis nihil enim velit necessitatibus quo est voluptatem, obcaecati libero ipsam veritatis doloremque iure ducimus eius fuga at excepturi! Cum.
            Numquam nobis fuga culpa suscipit, atque velit distinctio deserunt perspiciatis doloremque expedita tempora necessitatibus cumque qui est esse sequi at natus dolorum iste voluptate enim quae praesentium molestiae. Aut, ut!
            Corrupti hic deleniti similique voluptatem quidem repellendus nobis sequi animi numquam at adipisci necessitatibus obcaecati, rerum saepe ullam, quis quam odit, quibusdam dicta culpa. Dolor iure asperiores ducimus debitis sequi?
            Tempore ducimus temporibus quidem eos dolore! Id adipisci natus exercitationem magnam, sunt cupiditate possimus perspiciatis, animi, vel aliquam vitae at soluta aperiam. Explicabo excepturi molestias sunt tempora tempore. Adipisci, labore?
            Enim veniam quos odio dolor laborum voluptatibus. Nobis deleniti laboriosam nihil maxime, fugit possimus reprehenderit, doloribus, error repellendus assumenda vitae beatae voluptates voluptate. Vero repudiandae, dicta eveniet labore blanditiis laudantium.
        </div>
    );
}

export default HOME;
